---
- name: create VMs
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - ../group_vars/all.yml  # Adjust the path if necessary
  roles:
    - { role: ../roles/create_vms, tags: 'create_vms' }