---
- name: Create or clone the VM
  community.general.proxmox_kvm:
    api_host: "{{ PROXMOX_API_HOST }}"
    api_user: "{{ PROXMOX_API_USERNAME }}"
    api_password: "{{ PROXMOX_API_PASSWORD }}"
    node: "{{ PROXMOX_NODE }}"
    clone: "{{ CLONE_TEMPLATE_NAME }}"
    name: "{{ MACHINE_NAME }}"
    state: present
    timeout: "{{ PROXMOX_TIMEOUT }}"
  register: cloned_vm
  when: not vm_exists