---
- name: Create a VM from a template
  import_tasks: create_vm.yml

- name: Configure the VM server settings
  import_tasks: server_config.yml

- name: Configure VM networking
  import_tasks: network_config.yml

- name: Start the VM
  import_tasks: start_vm.yml