- name: Update network settings using qm command
  ansible.builtin.shell: |
    qm set {{ cloned_vm.vmid }} --net0 {{ NETWORK_INTERFACE_MODEL }},bridge={{ NETWORK_BRIDGE }},macaddr={{ MAC_ADDRESS }}
  register: resul
- name: Show result of qm set command
  ansible.builtin.debug:
    msg: "{{ result.stdout }}"
