- name: Update VM configuration (CPU, Memory, Storage)
  community.general.proxmox_kvm:
    api_host: "{{ PROXMOX_API_HOST }}"
    api_user: "{{ PROXMOX_API_USERNAME }}"
    api_password: "{{ PROXMOX_API_PASSWORD }}"
    node: "{{ PROXMOX_NODE }}"
    vmid: "{{ cloned_vm.vmid }}"
    cores: "{{ CPU_CORES }}"
    sockets: "{{ CPU_SOCKETS }}"
    memory: "{{ MEMORY_SIZE }}"
    scsi:
      size: "{{ DISK_SIZE }}"
      storage: "{{ PROXMOX_STORAGE }}"
    update: true
  when: cloned_vm.vmid is defined
